-- Tạo database QUANLYTRAMTRON
CREATE DATABASE QUANLYTRAMTRON
GO

USE QUANLYTRAMTRON
GO

-- Bảng NGUOIDUNG (dùng cho đăng nhập)
CREATE TABLE NGUOIDUNG (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USERNAME NVARCHAR(50) UNIQUE NOT NULL,
    PASSWORD NVARCHAR(50) NOT NULL,
    HOTEN NVARCHAR(100),
    DIACHI NVARCHAR(200),
    CAPDO NVARCHAR(20) CHECK (CAPDO IN (N'Quản lý', N'Vận hành')),
    EMAIL NVARCHAR(100),
    DANGNHAPCUOI DATETIME,
	QUYEN NVARCHAR(MAX) NULL
)
GO

-- Bảng KHACHHANG
CREATE TABLE KHACHHANG (
    MAKHACH INT IDENTITY(1,1) PRIMARY KEY,
    TENKHACH NVARCHAR(100) NOT NULL,
    DIACHI NVARCHAR(200),
    DIENTHOAI NVARCHAR(20)
)
GO

-- Bảng CONGTRINH
CREATE TABLE CONGTRINH (
    MACONGTRINH INT IDENTITY(1,1) PRIMARY KEY,
    DIADIEM NVARCHAR(200) NOT NULL,
    HANGMUC NVARCHAR(200),
    THIETBIBOM NVARCHAR(200)
)
GO

-- Bảng XE
CREATE TABLE XE (
    MAXE INT IDENTITY(1,1) PRIMARY KEY,
    BIENSO NVARCHAR(20) NOT NULL,
    LAIXE NVARCHAR(100) NOT NULL
)
GO

-- Bảng PHUGIA
CREATE TABLE PHUGIA (
    MAPHUGIA INT IDENTITY(1,1) PRIMARY KEY,
    TENPHUGIA NVARCHAR(100) NOT NULL,
    GHICHU NVARCHAR(500)
)
GO

-- Bảng KINHDOANH
CREATE TABLE KINHDOANH (
    MAKINHDOANH INT IDENTITY(1,1) PRIMARY KEY,
    TENKINHDOANH NVARCHAR(200) NOT NULL
)
GO

-- Bảng TRAM
CREATE TABLE TRAM (
    MATRAM INT IDENTITY(1,1) PRIMARY KEY,
    TENTRAM NVARCHAR(200) NOT NULL,
    CHUTRAM NVARCHAR(200),
    DIADIEM NVARCHAR(200),
    CONGSUAT NVARCHAR(50),
    DIENTHOAI NVARCHAR(20),
    TRANGTHAI NVARCHAR(20) DEFAULT 'Online',
    DUONGDANRUNTIME NVARCHAR(500),
    LOAICAPPHOI NVARCHAR(50)
)
GO

-- Bảng DONHANG (đã bổ sung MAXE và DIACHI)
CREATE TABLE DONHANG (
    MADONHANG INT IDENTITY(1,1) PRIMARY KEY,
    NGAYDAT DATETIME NOT NULL DEFAULT GETDATE(),
    KYHIEUDON NVARCHAR(50),
    SOPHIEU NVARCHAR(50),
    KHOILUONG DECIMAL(10,2),
    TICHLUY DECIMAL(10,2),
    MATRAM INT FOREIGN KEY REFERENCES TRAM(MATRAM),
    MAKHACH INT FOREIGN KEY REFERENCES KHACHHANG(MAKHACH),
    MAKINHDOANH INT FOREIGN KEY REFERENCES KINHDOANH(MAKINHDOANH),
    MACONGTRINH INT FOREIGN KEY REFERENCES CONGTRINH(MACONGTRINH),
    MAXE INT FOREIGN KEY REFERENCES XE(MAXE),   -- ✅ Bổ sung
    NHANVIENKD NVARCHAR(100),
    DIACHI NVARCHAR(200),                      -- ✅ Bổ sung
    HOATDONG BIT DEFAULT 1
)
GO

-- Bảng CAPPHOI
CREATE TABLE CAPPHOI (
    MACAPPHOI INT IDENTITY(1,1) PRIMARY KEY,
    STT INT,
    MACBETONG NVARCHAR(50) NOT NULL,
    CUONGDO NVARCHAR(50),
    COTLIEUMAX NVARCHAR(50),
    DOSUT NVARCHAR(20),
    TONGSLVATTU DECIMAL(10,2),
    GHICHU NVARCHAR(500)
)
GO

-- Bảng VATTU
CREATE TABLE VATTU (
    MAVATTU INT IDENTITY(1,1) PRIMARY KEY,
    TENVATTU NVARCHAR(100) NOT NULL,
    DONVITINH NVARCHAR(50),
    HESOQUYDOI DECIMAL(10,2),
    TONKHO DECIMAL(10,2) DEFAULT 0
)
GO

-- Bảng KHO
CREATE TABLE KHO (
    MAKHO INT IDENTITY(1,1) PRIMARY KEY,
    NGAYGIAODICH DATETIME NOT NULL DEFAULT GETDATE(),
    LOAIGIAODICH NVARCHAR(20) CHECK (LOAIGIAODICH IN ('Nhập', 'Xuất', 'Tịnh kho')),
    MAVATTU INT FOREIGN KEY REFERENCES VATTU(MAVATTU),
    SOPHIEU NVARCHAR(50),
    SOHOPDONG NVARCHAR(50),
    SOLUONG DECIMAL(10,2),
    SOLUONGKG DECIMAL(10,2),
    PHUONGTIEN NVARCHAR(100),
    LAIXE NVARCHAR(100),
    DONVIVANCHUYEN NVARCHAR(100),
    NHACUNGCAP NVARCHAR(200),
    TONKHO DECIMAL(10,2),
    GHICHU NVARCHAR(500),
    MATRAM INT FOREIGN KEY REFERENCES TRAM(MATRAM)
)
GO

-- Bảng PHIEUXUAT
CREATE TABLE PHIEUXUAT (
    MAPHIEUXUAT INT IDENTITY(1,1) PRIMARY KEY,
    SOPHIEU NVARCHAR(50) NOT NULL,
    NGAYXUAT DATETIME NOT NULL DEFAULT GETDATE(),
    MADONHANG INT FOREIGN KEY REFERENCES DONHANG(MADONHANG),
    MAXE INT FOREIGN KEY REFERENCES XE(MAXE),
    MAKHACH INT FOREIGN KEY REFERENCES KHACHHANG(MAKHACH),
    MACONGTRINH INT FOREIGN KEY REFERENCES CONGTRINH(MACONGTRINH),
    MACBETONG NVARCHAR(50),
    KHOILUONG DECIMAL(10,2),
    THOIGIANTRON DATETIME,
    GHICHU NVARCHAR(500),
    MATRAM INT FOREIGN KEY REFERENCES TRAM(MATRAM),
    THOIGIANBATDAU DATETIME,
    THOIGIANKETTHUC DATETIME,
    THIETBIBOM NVARCHAR(100),
    SUDUNGBOM BIT DEFAULT 0
)
GO

-- Bảng CHITIETPHIEUXUAT
CREATE TABLE CHITIETPHIEUXUAT (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MAPHIEUXUAT INT FOREIGN KEY REFERENCES PHIEUXUAT(MAPHIEUXUAT),
    MAVATTU INT FOREIGN KEY REFERENCES VATTU(MAVATTU),
    SOLUONG DECIMAL(10,2),
    GHICHU NVARCHAR(500)
)
GO

-- Bảng CAIDATCHUNG
CREATE TABLE CAIDATCHUNG (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    THIETLAP NVARCHAR(100) NOT NULL,
    GIATRI NVARCHAR(500),
    GHICHU NVARCHAR(500)
)
GO

-- Bảng EMAILCONFIG
CREATE TABLE EMAILCONFIG (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MATRAM INT FOREIGN KEY REFERENCES TRAM(MATRAM),
    CHEDOGUI NVARCHAR(20) CHECK (CHEDOGUI IN ('Không gửi', 'Hàng giờ', 'Hàng ngày')),
    GUITUNGAY DATETIME,
    MAUBAOCAO NVARCHAR(20) CHECK (MAUBAOCAO IN ('Tổng', 'Chi tiết')),
    GHICHU NVARCHAR(500)
)
GO

-- Bảng DONGBO
CREATE TABLE DONGBO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MATRAM INT FOREIGN KEY REFERENCES TRAM(MATRAM),
    KIEUDONGBO NVARCHAR(50) CHECK (KIEUDONGBO IN ('Từ Máy Trạm → Máy Chủ', 'Từ Máy Chủ → Máy Trạm', 'Không đồng bộ')),
    LANCUOIDONGBO DATETIME,
    TRANGTHAI NVARCHAR(20),
    GHICHU NVARCHAR(500)
)
GO

-- Bảng LICHSUDANGNHAP
CREATE TABLE LICHSUDANGNHAP (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    IDNGUOIDUNG INT FOREIGN KEY REFERENCES NGUOIDUNG(ID),
    THOIGIANDANGNHAP DATETIME NOT NULL DEFAULT GETDATE(),
    IPADDRESS NVARCHAR(50),
    TRANGTHAI NVARCHAR(20)
)
GO

-- Bảng CUA_VATTU
CREATE TABLE CUA_VATTU (
    MACUA INT IDENTITY(1,1) PRIMARY KEY,
    STT INT,
    TENTRAM NVARCHAR(200),
    LOAIVATTU NVARCHAR(100),
    TENCUA NVARCHAR(100) NOT NULL,
    HESOQUYDOI DECIMAL(10,2),
    DONVITINH NVARCHAR(50)
)
GO

-- Bảng THIETLAPIN
CREATE TABLE THIETLAPIN (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TENMAUIN NVARCHAR(50) NOT NULL,
    LOAIIN NVARCHAR(20) CHECK (LOAIIN IN (N'Chi tiết', N'Tổng hợp')),
    GHICHU NVARCHAR(500)
)
GO

-- Bảng THONGKE
CREATE TABLE THONGKE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MADONHANG INT FOREIGN KEY REFERENCES DONHANG(MADONHANG),
    MAKHACH INT FOREIGN KEY REFERENCES KHACHHANG(MAKHACH),
    MACONGTRINH INT FOREIGN KEY REFERENCES CONGTRINH(MACONGTRINH),
    MAKINHDOANH INT FOREIGN KEY REFERENCES KINHDOANH(MAKINHDOANH),
    MAXE INT FOREIGN KEY REFERENCES XE(MAXE),
    MACBETONG NVARCHAR(50),
    KYHIEUDON NVARCHAR(50),
    SOLUONG DECIMAL(10,2),
    NGAYTHONGKE DATETIME DEFAULT GETDATE(),
    LOAITHONGKE NVARCHAR(20) CHECK (LOAITHONGKE IN ('Chi tiết', 'Tổng hợp', 'Số chuyến'))
)
GO

-- Bảng CHITIET_VATTU_THONGKE
CREATE TABLE CHITIET_VATTU_THONGKE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    IDTHONGKE INT FOREIGN KEY REFERENCES THONGKE(ID),
    MAVATTU INT FOREIGN KEY REFERENCES VATTU(MAVATTU),
    SOLUONG DECIMAL(10,2)
)
GO

-- Thêm dữ liệu mẫu cho bảng NGUOIDUNG
INSERT INTO NGUOIDUNG (USERNAME, PASSWORD, HOTEN, CAPDO, QUYEN) 
VALUES 
(N'admin', N'123456', N'Administrator', N'Quản lý', N'Danh mục, Mác bê tông, Thống kê, Cài đặt, Kho'),
(N'user1', N'123456', N'Người dùng 1', N'Vận hành', N'Danh mục, Mác bê tông'),
(N'user2', N'123456', N'Người dùng 2', N'Vận hành', N'Thống kê, Kho'),
(N'quanly', N'123456', N'Quản lý hệ thống', N'Quản lý', N'Danh mục, Mác bê tông, Thống kê, Cài đặt'),
(N'kho', N'123456', N'Nhân viên kho', N'Vận hành', N'Kho')
GO

-- Thêm dữ liệu mẫu cho bảng TRAM
INSERT INTO TRAM (TENTRAM, CHUTRAM, DIADIEM, CONGSUAT, DIENTHOAI, TRANGTHAI) 
VALUES 
(N'CÔNG TY CỔ PHẦN BÊ TÔNG TÂY ĐÔ', N'CÔNG TY CỔ PHẦN BÊ TÔNG TÂY ĐÔ', N'T 90 Băng Tải - Hậu Giang', N'90m3', N'123456789', N'Online'),
(N'TRẠM THỬ NGHIỆM', N'TRẠM THỬ NGHIỆM', N'Địa điểm thử nghiệm', N'82m3', N'987654321', N'Online'),
(N'82m3 - T 82 Xe kíp - M', N'TRẠM 82', N'TP.HCM', N'82m3', N'0912345678', N'Online'),
(N'150m3 - T 150 - Ô Môn 1', N'TRẠM 150', N'Cần Thơ', N'150m3', N'0913456789', N'Online'),
(N'150m3 - T 150 - Ô Môn 2', N'TRẠM 150', N'Cần Thơ', N'150m3', N'0914567890', N'Online')
GO

-- Thêm dữ liệu mẫu cho bảng KHACHHANG
INSERT INTO KHACHHANG (TENKHACH, DIACHI) 
VALUES 
(N'ANH DƯƠNG', N''),
(N'CTY TNHH TM-XD VẠN AN PHÁT CT', N''),
(N'ANH GIÀU', N''),
(N'CTY HÙNG THỊNH', N''),
(N'CTY 585', N''),
(N'CTY THIÊN MINH', N''),
(N'CTY BẢO LONG', N''),
(N'CTY TNHH CT MINH THÀNH', N''),
(N'ANH TÂM', N''),
(N'NGUYỄN VĂN CẢNH', N''),
(N'Công ty Xây dựng An Phát', N'Quận 1, TP.HCM'),
(N'Công ty Hoà Bình', N'Quận 7, TP.HCM'),
(N'Công ty Nam Thành', N'Bình Thạnh, TP.HCM')
GO

-- Thêm dữ liệu mẫu cho bảng CONGTRINH
INSERT INTO CONGTRINH (DIADIEM, HANGMUC, THIETBIBOM) 
VALUES 
(N'Công trình A', N'Xây dựng hạ tầng', N'Bơm nước 3HP'),
(N'Công trình B', N'Lắp đặt điện', N'Bơm công nghiệp 5HP'),
(N'Công trình C', N'Thi công PCCC', N'Bơm cứu hỏa'),
(N'Công trình D', N'Nhà xưởng sản xuất', N'Máy nén khí 15kW'),
(N'Công trình E', N'Chung cư cao tầng', N'Thang máy tải khách'),
(N'Công trình F', N'Cầu đường', N'Máy phát điện 100kVA'),
(N'Công trình G', N'Kho bãi logistics', N'Hệ thống lạnh công nghiệp'),
(N'Công trình H', N'Khu đô thị', N'Máy bơm nước thải 7.5HP'),
(N'KHO BẠC NHÀ NƯỚC HẬU GIANG', N'Kho bạc', N'Máy bơm công nghiệp'),
(N'QL61C, H.CHÂU THÀNH', N'Cầu đường', N'Máy xúc'),
(N'KCN TÂN PHÚ THẠNH', N'Khu công nghiệp', N'Máy trộn bê tông'),
(N'QL1A, P.7, TP.VĨNH LONG', N'Quốc lộ', N'Máy đầm'),
(N'CẦU CÁI RĂNG - CẦN THƠ', N'Cầu', N'Máy khoan'),
(N'KDC HƯNG PHÚ 1, CẦN THƠ', N'Khu dân cư', N'Máy bơm bê tông'),
(N'KĐT MỚI NAM CẦN THƠ', N'Khu đô thị', N'Máy trộn bê tông'),
(N'KCN TRÀ NÓC 2, CẦN THƠ', N'Khu công nghiệp', N'Máy nâng')
GO

-- Thêm dữ liệu mẫu cho bảng XE
INSERT INTO XE (BIENSO, LAIXE) 
VALUES 
(N'51C-34567', N'Nguyễn Văn An'),
(N'51D-67890', N'Trần Quốc Bảo'),
(N'60A-24680', N'Lê Minh Cường'),
(N'65H-11223', N'Phạm Thị Dung'),
(N'66B-33445', N'Huỳnh Tấn Đạt'),
(N'67C-55667', N'Ngô Hoàng Phúc'),
(N'68D-77889', N'Đỗ Thị Hồng'),
(N'69E-99001', N'Bùi Văn Hùng'),
(N'51D-12345', N'Nguyễn Văn An'),
(N'51D-67890', N'Trần Quốc Bảo'),
(N'51C-54321', N'Lê Minh Cường')
GO

-- Thêm dữ liệu mẫu cho bảng PHUGIA
INSERT INTO PHUGIA (TENPHUGIA, GHICHU) 
VALUES 
(N'Phụ gia siêu dẻo', N'Tăng độ chảy, giảm nước khi trộn bê tông'),
(N'Phụ gia chậm đông kết', N'Kéo dài thời gian ninh kết, phù hợp công trình lớn'),
(N'Phụ gia chống thấm', N'Tăng khả năng chống thấm cho bê tông và vữa'),
(N'Phụ gia khoáng hoạt tính', N'Cải thiện cường độ và độ bền lâu dài'),
(N'Phụ gia cuốn khí', N'Tăng khả năng chống nứt và chống băng giá'),
(N'Phụ gia tăng nhanh đông kết', N'Rút ngắn thời gian ninh kết, thi công nhanh'),
(N'Phụ gia giảm co ngót', N'Giảm hiện tượng nứt do co ngót'),
(N'Phụ gia khoáng mịn (Silica Fume)', N'Tăng độ đặc chắc, chống xâm thực hóa chất')
GO

-- Thêm dữ liệu mẫu cho bảng KINHDOANH
INSERT INTO KINHDOANH (TENKINHDOANH) 
VALUES 
(N'Công ty TNHH Thương mại An Phát'),
(N'Công ty CP Xây dựng Minh Tâm'),
(N'Doanh nghiệp Tư nhân Hoàng Gia'),
(N'Công ty TNHH SX - TM Đại Thành'),
(N'Công ty CP Vận tải Đông Dương'),
(N'Công ty TNHH Cơ khí Tân Tiến'),
(N'Công ty CP VLXD Sài Gòn'),
(N'Doanh nghiệp Tư nhân Hòa Bình')
GO

-- Thêm dữ liệu mẫu cho bảng CAUPHOI
INSERT INTO CAPPHOI (STT, MACBETONG, CUONGDO, COTLIEUMAX, DOSUT) 
VALUES 
(1, N'C30R28-10±2', N'25', N'20', N'10±2'),
(2, N'C20R28-12±2', N'20', N'16', N'12±2'),
(3, N'C25R28-14±2', N'22', N'18', N'14±2'),
(4, N'C35R28-10±2', N'28', N'22', N'10±2'),
(5, N'C40R28-16±2', N'30', N'24', N'16±2'),
(6, N'C25R14-12±2', N'21', N'17', N'12±2'),
(7, N'C30R14-10±2', N'24', N'19', N'10±2'),
(8, N'C20R14-14±2', N'18', N'15', N'14±2')
GO

-- Thêm dữ liệu mẫu cho bảng VATTU
INSERT INTO VATTU (TENVATTU, DONVITINH, HESOQUYDOI) 
VALUES 
(N'Xi măng', N'Bao', N'50'),
(N'Cát', N'm3', N'1500'),
(N'Đá', N'm3', N'1600'),
(N'Nước', N'L', N'1'),
(N'Phụ gia siêu dẻo', N'Kg', N'1'),
(N'Phụ gia chậm đông kết', N'Kg', N'1'),
(N'Thép', N'Thanh', N'12'),
(N'Gạch', N'Viên', N'2.5')
GO

-- Thêm dữ liệu mẫu cho bảng DONHANG
INSERT INTO DONHANG (NGAYDAT, KYHIEUDON, SOPHIEU, KHOILUONG, TICHLUY, MAKHACH, DIACHI) 
VALUES 
('2025-07-27', N'A01', N'0', 24, 0, 2, N'KHO BẠC NHÀ NƯỚC HẬU GIANG'),
('2025-07-05', N'A02', N'0', 20, 0, 3, N'QL61C, H.CHÂU THÀNH'),
('2025-07-10', N'A03', N'0', 15, 0, 4, N'KCN TÂN PHÚ THẠNH'),
('2025-07-15', N'A04', N'0', 30, 0, 5, N'QL1A, P.7, TP.VĨNH LONG'),
('2025-07-20', N'A05', N'0', 18, 0, 6, N'CẦU CÁI RĂNG - CẦN THƠ'),
('2025-07-22', N'A06', N'0', 25, 0, 7, N'KDC HƯNG PHÚ 1, CẦN THƠ'),
('2025-07-24', N'A07', N'0', 40, 0, 8, N'KĐT MỚI NAM CẦN THƠ'),
('2025-07-30', N'A08', N'0', 12, 0, 9, N'KCN TRÀ NÓC 2, CẦN THƠ')
GO

-- Thêm dữ liệu mẫu cho bảng CUA_VATTU
INSERT INTO CUA_VATTU (STT, TENTRAM, LOAIVATTU, TENCUA, HESOQUYDOI, DONVITINH) 
VALUES 
(1, N'Trạm A', N'Xi măng', N'Cửa số 1', N'1.00', N'Bao'),
(2, N'Trạm B', N'Cát', N'Cửa số 2', N'0.80', N'Khối')
GO

-- Thêm dữ liệu mẫu cho bảng CAIDATCHUNG
INSERT INTO CAIDATCHUNG (THIETLAP, GIATRI) 
VALUES 
(N'SoTram', N'2'),
(N'LoaiCapPhoi', N'1'),
(N'TenCongTy', N'CÔNG TY CỔ PHẦN BÊ TÔNG TÂY ĐÔ')
GO

-- Thêm dữ liệu mẫu cho bảng THIETLAPIN
INSERT INTO THIETLAPIN (TENMAUIN, LOAIIN) 
VALUES 
(N'Mẫu 1', N'Chi tiết'),
(N'Mẫu 2', N'Chi tiết'),
(N'Mẫu 3', N'Chi tiết'),
(N'Mẫu 4', N'Tổng hợp')
GO
